// Generated by Prisma — assumes prisma + dotenv are installed.
import path from "node:path";
import dotenv from "dotenv";
import { defineConfig } from "prisma/config";

// npm workspaces run this from apps/api, but .env lives at the monorepo root.
dotenv.config({ path: path.resolve(__dirname, "../../.env") });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
